# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APASlapApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APASlapApp
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'	
  pod 'Firebase/Messaging'	
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'

  pod 'FaveButton', '~> 2.0.3'

  pod 'DateToolsSwift'


end
